version: '3.9'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nandemo
      MYSQL_USER: nandemo
      MYSQL_PASSWORD: nandemo
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  web:
    build: .
    volumes:
      - .:/workspace
    environment:
      TZ: Asia/Tokyo
    ports:
      - "8070:8070"
    depends_on:
      - db